dist: xenial
language: python
jobs:
  include:
  - python: "3.2"
    dist: trusty
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install restructuredtext-lint
script:
- shellcheck git*
- python3 -m pydiatra .
- python3 -m pyflakes .
- printf 'From\72 Jakub Wilk <notifications@github.com>\nX-GitHub-Sender\72 jwilk\n\ntest\n' | ./mail-filter
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
