#!/usr/bin/env bash

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if [ $# -ne 2 ]
then
    printf 'Usage: %s REPO NEW-OWNER\n' "${0##*/}" >&2
    exit 1
fi
repo="$1"
repo=${repo#https://github.com/}
new_owner="$2"
url="https://api.github.com/repos/$repo/transfer"
printf 'POST %s\n' "$url" >&2
gh api "$url" -f new_owner="$new_owner" --jq '.html_url'

# vim:ts=4 sts=4 sw=4 et
