#!/usr/bin/env bash

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage: %s <reaction> <url>\n' "${0##*/}"
    printf 'Reactions: +1 -1 :D :/ <3 \o/\n'
    printf 'URLs: https://github.com/<owner>/<repo>/issues/<n>\n'
}

set -e -u
if [ $# -ne 2 ]
then
    usage >&2
    exit 1
fi
reaction="$1"
url="$2"
if [ "$reaction" = '+1' ] || [ "$reaction" = '-1' ]
then
    :
elif [ "$reaction" = ':D' ]
then
    reaction=laugh
elif [ "$reaction" = ':/' ]
then
    reaction=confused
elif [ "$reaction" = '<3' ]
then
    reaction=heart
elif [ "$reaction" = '\o/' ]
then
    reaction=hooray
else
    usage >&2
    exit 1
fi
re='^https://github[.]com/([^/]+)/([^/]+)/(issues|pull)/([0-9]+)(#issuecomment-([0-9]+))?$'
if [[ $url =~ $re ]]
then
    owner=${BASH_REMATCH[1]}
    repo=${BASH_REMATCH[2]}
    number=${BASH_REMATCH[4]}
    comment=${BASH_REMATCH[6]}
else
    usage >&2
    exit 1
fi
url='https://api.github.com/repos'
if [ -n "$comment" ]
then
    url="$url/$owner/$repo/issues/comments/$comment/reactions"
else
    url="$url/$owner/$repo/issues/$number/reactions"
fi
json='{"content":"'"$reaction"'"}'
printf '%s %s\n' POST "$url" >&2
gh api "$url" --input - <<< "$json" > /dev/null

# vim:ts=4 sts=4 sw=4 et
