#!/usr/bin/env bash

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if [ $# -eq 0 ]
then
    printf 'Usage: %s REPO [REPO...]\n' "${0##*/}" >&2
    exit 1
fi
for repo in "$@"
do
    repo=${repo#https://github.com/}
    gh repo edit --description='[boring fork, please ignore]' --homepage='' "$repo"
done

# vim:ts=4 sts=4 sw=4 et
