#!/bin/bash

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
cacert=$(git -C / config --get-urlmatch http.sslCAInfo https://api.github.com/)
github_token=$(sed -n -r -e 's/token\s*=\s*//p' "${XDG_DATA_HOME:-$HOME/.config}"/cligh/cligh.conf)
user=$(git -C / config --get hub.username)-forks
json=$(jo "organization=$user")
for repo in "$@"
do
    [ "$repo" = "${repo#*/}" ] && repo="$USER/$repo"
    url="https://api.github.com/repos/$repo/forks"
    printf 'POST %s\n' "$url"
    res=$(curl \
        --silent --fail --show-error \
        --capath /nonexistent --cacert "$cacert" \
        -K <(printf "header = \"Authorization: token %s\"\n" "$github_token") \
        -H 'User-Agent: github-toolbox (https://github.com/jwilk/github-toolbox)' \
        -H 'Accept: application/vnd.github.v3+json' \
        -X POST --data "$json" \
        "$url"
    )
    jq -r '.["html_url"]' <<<"$res"
done

# vim:ts=4 sts=4 sw=4 et
