#!/usr/bin/env bash

# Copyright © 2017-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

get_curl_config()
{
    printf 'header = "Authorization: token %s"\n' "$github_token"
    if [ -n "$cacert" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

set -e -u
cacert=$(git -C / config --get-urlmatch http.sslCAInfo https://api.github.com/) || true
github_token=$(perl -n -E '/^token\s*=\s*(\S+)/ and say $1' "${XDG_DATA_HOME:-$HOME/.config}"/cligh/cligh.conf)
if [ $# -eq 0 ]
then
    printf 'Usage: %s REPO [REPO...]\n' "${0##*/}" >&2
    exit 1
fi
for repo in "$@"
do
    if [ "$repo" = "${repo%/*}" ]
    then
        url='user/repos'
    else
        url="orgs/${repo%/*}/repos"
        repo="${repo#*/}"
    fi
    url="https://api.github.com/$url"
    json=$(jq -n '{name: $repo, has_wiki: false, has_projects: false}' --arg repo "$repo")
    printf 'POST %s\n' "$url" >&2
    res=$(curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'User-Agent: github-toolbox (https://github.com/jwilk/github-toolbox)' \
        -H 'Accept: application/vnd.github.v3+json' \
        -X POST --data "$json" \
        "$url"
    )
    jq -r '.["html_url"]' <<<"$res"
done

# vim:ts=4 sts=4 sw=4 et
