#!/bin/bash

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

get_curl_config()
{
    printf "header = \"Authorization: token %s\"\n" "$github_token"
    if [ -n "$cacert" ]
    then
        printf 'capath = "/nonexistent"\n'
        printf 'cacert = "%s"\n' "$cacert"
    fi
}

set -e -u
cacert=$(git -C / config --get-urlmatch http.sslCAInfo https://api.github.com/) || true
github_token=$(sed -n -r -e 's/^token\s*=\s*//p' "${XDG_DATA_HOME:-$HOME/.config}"/cligh/cligh.conf)
for repo in "$@"
do
    if [ "$repo" = "${repo%/*}" ]
    then
        url='user/repos'
    else
        url="orgs/${repo%/*}/repos"
        repo="${repo#*/}"
    fi
    url="https://api.github.com/$url"
    json=$(jo -B name="$repo" has_wiki@0 has_projects@0)
    printf 'POST %s\n' "$url"
    res=$(curl \
        --silent --fail --show-error \
        -K <(get_curl_config) \
        -H 'User-Agent: github-toolbox (https://github.com/jwilk/github-toolbox)' \
        -H 'Accept: application/vnd.github.v3+json' \
        -X POST --data "$json" \
        "$url"
    )
    jq -r '.["html_url"]' <<<"$res"
done

# vim:ts=4 sts=4 sw=4 et
