#!/usr/bin/env bash

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
method=PUT
[ "${0%%*-unstar}" ] || method=DELETE
if [ $# -eq 0 ]
then
    printf 'Usage: %s REPO [REPO...]\n' "${0##*/}" >&2
    exit 1
fi
for repo in "$@"
do
    repo=${repo#https://github.com/}
    url="https://api.github.com/user/starred/$repo"
    printf '%s %s\n' "$method" "$url" >&2
    gh api --method="$method" "$url"
done

# vim:ts=4 sts=4 sw=4 et
