#!/bin/sh

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

##>> open .git/HUB_EDITMSG in grip(1)

set -e -u
context=$(git config --get hub.upstream)
port=$(( 2000 + $(od -An -N2 -i /dev/urandom) % 1000))
path=$(git rev-parse --git-dir)/HUB_EDITMSG
exec grip -b --user-content --context "$context" "$path" "localhost:$port"

# vim:ts=4 sts=4 sw=4 et
