#!/usr/bin/env bash

# Copyright © 2017-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
if [ $# -eq 0 ]
then
    printf 'Usage: %s REPO [REPO...]\n' "${0##*/}" >&2
    exit 1
fi
for repo in "$@"
do
    if [ "$repo" = "${repo%/*}" ]
    then
        url='user/repos'
    else
        url="orgs/${repo%/*}/repos"
        repo="${repo#*/}"
    fi
    url="https://api.github.com/$url"
    printf 'POST %s\n' "$url" >&2
    gh api -F name="$repo" -F has_wiki=false -F has_projects=false "$url" --jq='.["html_url"]'
done

# vim:ts=4 sts=4 sw=4 et
