#!/usr/bin/env python3

# Copyright © 2017-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import email.generator
import email.utils
import sys

def main():
    msg = email.message_from_binary_file(sys.stdin.buffer)
    sender = msg['X-GitHub-Sender']
    from_hdr = msg['From']
    name, addr = email.utils.parseaddr(from_hdr)
    if sender is not None:
        from_hdr = email.utils.formataddr((name, sender + '@users.noreply.github.com'))
        del msg['From']
        msg['From'] = from_hdr
    generator = email.generator.BytesGenerator(sys.stdout.buffer, mangle_from_=False)
    generator.flatten(msg, unixfrom=True)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
