#!/usr/bin/env python3

# Copyright © 2017-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import email.generator
import email.headerregistry
import email.policy
import sys

lambda: (yield from 0)  # Python >= 3.3 is required

def main():
    msg = email.message_from_binary_file(sys.stdin.buffer, policy=email.policy.default)
    sender = msg['X-GitHub-Sender']
    [from_hdr] = msg['From'].addresses
    if sender is not None:
        from_hdr = email.headerregistry.Address(
            display_name=from_hdr.display_name,
            username=sender,
            domain='users.noreply.github.com'
        )
        del msg['From']
        msg['From'] = from_hdr
    generator = email.generator.BytesGenerator(sys.stdout.buffer, mangle_from_=False)
    generator.flatten(msg, unixfrom=True)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
