name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
        - os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: run shellcheck
      run: |
        shellcheck github*
    - name: run tests
      run: |
        JWILK_GITHUB_TOOLBOX_NETWORK_TESTING=1 prove -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
  python:
    strategy:
      matrix:
        include:
        - python: '3.5'
          os: ubuntu-20.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: smoke test
      run: prove -v t/mail-filter.t

# vim:ts=2 sts=2 sw=2 et
