name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04
        - os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: run shellcheck
      run: |
        shellcheck github*
    - name: run tests
      run: |
        xdg="${XDG_DATA_HOME:-$HOME/.config}"
        mkdir -m 700 "$xdg/cligh/"
        cat <<< "token=${{secrets.GITHUB_TOKEN}}" > "$xdg/cligh/cligh.conf"
        JWILK_GITHUB_TOOLBOX_NETWORK_TESTING=1 prove -v
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
      if: matrix.os != 'ubuntu-18.04'
  python:
    strategy:
      matrix:
        include:
        - python-version: '3.3'
          os: ubuntu-18.04
          pyflakes: 'pyflakes<2'
        - python-version: '3.4'
          os: ubuntu-18.04
        - python-version: '3.5'
          os: ubuntu-18.04
        - python-version: '3.6'
          os: ubuntu-20.04
        - python-version: '3.7'
          os: ubuntu-20.04
        - python-version: '3.8'
          os: ubuntu-20.04
        - python-version: '3.9'
          os: ubuntu-20.04
        - python-version: '3.10'
          os: ubuntu-20.04
        - python-version: '3.11-dev'
          os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install $pyflakes
        python3 -m pyflakes .
      env:
        pyflakes: ${{matrix.pyflakes || 'pyflakes'}}
    - name: smoke test
      run: prove -v t/mail-filter.t

# vim:ts=2 sts=2 sw=2 et
